### ISSUE TITLE
no reaction after installation

### ISSUE THREAD

**Issue by katrinleinweber** [baig/brackets-zotero#4]
I followed the [Install & Use instructions](http://wasifbaig.com/brackets-zotero/) on Mac OS X 10.9.5 in [Brackets 1.3](https://github.com/adobe/brackets/releases/tag/release-1.3) and [Zotero for Firefox 4.0.26.4](https://github.com/zotero/zotero/releases/tag/4.0.26.4) with the [BetterBibTeX addon](https://github.com/ZotPlus/zotero-better-bibtex/releases/tag/0.11.16). Neither the `Z` button, nor `Ctrl+Shift+Z` causes any reaction.

Is it supposed to find the HTTP export location automatically?

**Comment by baig** [comment]
The keyboard short-cut on Mac is `Alt-Z` and Zotero (or Firefox if using Zotero from within Firefox) should be running in order to use this extension.

**Comment by baig** [comment]
Press `F5` to reload Brackets with extensions and see if it works.

**Comment by katrinleinweber** [comment]
Thanks! I'm sorry to have to say though, that the situation remains unimproved.

**Comment by baig** [comment]
I'd appreciate if you upload a screenshot of the developer console, it will help me debug the issue.
1. Press `F5` to reload Brackets.
2. Press `F12` to open the developer console (you will need Chrome for this).
3. Grab a screenshot of the dev console and then upload it in the next comment.

**Comment by katrinleinweber** [comment]
I don't have Chrome installed, sorry. Is it maybe needed for this whole setup to work?

This is the built-in dev console after several time reloading Brackets and clicking the Zotero Integration button.
![brackets-zotero-disconnect](https://cloud.githubusercontent.com/assets/9948149/8270775/6dfd4620-17f3-11e5-85d1-940a1f01126c.png)

**Comment by baig** [comment]
This is strange behavior. The plugin seems to be loaded and you have the right configuration. If there was some error either while initializing the plugin or when clicking the button, it should have been reported in the console but there is none. Have you tried restarting (not reloading) brackets. Sometimes Mac OS sends application to the background instead of quitting them.

**Comment by katrinleinweber** [comment]
I restarted, reloaded, rebooted, disabled and re-enabled the relevant addons several times. Maybe I'll find the time to reinstall and/or try it on Win7, but for now I'll have to excuse myself. Continuing the actual writing is more important, as I'm sure you'll understand.
