### ISSUE TITLE
schomd methods in BBT

### ISSUE THREAD

**Issue by retorquere** [baig/brackets-zotero#5]
In preparation for the impending mandatory Firefox extension signing, I need to rework the HTTP API I provide. Most of the API will work unchanged, but for the call to `schomd.bibtex` with format `json` I will have to introduce breaking changes. Do you still use this way of calling the method? I can't find it in your sources.

**Comment by baig** [comment]
Sorry for replying back so late. For this plugin, the only call to `schomd.bibtex` is on [line 209 in Zotero.js](https://github.com/baig/brackets-zotero/blob/master/src/Zotero.js#L209) and that too with [`format = format || "text";`](https://github.com/baig/brackets-zotero/blob/master/src/Zotero.js#L212). So you can safely introduce breaking changes to your API.

**Comment by retorquere** [comment]
Super, thanks. I'm done with the changes required for signing. The next hurdle is going to be Zotero 5.0 preparation -- quite likely more breaking changes will be required. I'll keep you posted.

**Comment by baig** [comment]
Thanks man! I really appreciate that.
